import type { Playbook } from '../../types';

export const playbooks: Playbook[] = [
  {
    id: 'PB-001',
    name: 'Brute Force / Password Spray Response',
    incidentCategory: 'Authentication',
    severity: 'high',
    overview: 'Credential-based attacks attempting to authenticate using guessed or leaked passwords. Includes brute force (single account, high volume) and password spray (many accounts, low volume per account).',
    whyItMatters: 'Successful credential compromise leads to unauthorized access, lateral movement, and potential data breaches. Domain Admin account compromise is catastrophic.',
    detectionIndicators: [
      'Event 4625 — >10 failures in 5 minutes from same source IP',
      'Event 4625 targeting multiple accounts from one IP (spray pattern)',
      'Event 4625 followed by Event 4624 from same source',
      'NTLM authentication failures at high volume',
    ],
    steps: [
      { id: 'step-1', stage: 'investigate', action: 'Identify attack pattern: brute force or spray?', description: 'If one account targeted = brute force. If many accounts from one IP = spray.', completed: false, priority: 'immediate' },
      { id: 'step-2', stage: 'investigate', action: 'Check for successful logons (4624) following failures', description: 'A 4624 after 4625 bursts confirms successful compromise.', completed: false, priority: 'immediate' },
      { id: 'step-3', stage: 'investigate', action: 'Determine geolocation of source IP', description: 'Impossible travel or Tor exit node IPs are strong malicious indicators.', completed: false, priority: 'immediate' },
      { id: 'step-4', stage: 'contain', action: 'Block source IP at firewall', description: 'Add the attacking IP to the deny list at the perimeter firewall.', completed: false, priority: 'immediate' },
      { id: 'step-5', stage: 'contain', action: 'Temporarily disable targeted accounts if privileged', description: 'If Domain Admin or sensitive service accounts were targeted, disable them pending investigation.', completed: false, priority: 'immediate' },
      { id: 'step-6', stage: 'contain', action: 'Revoke active sessions for compromised accounts', description: 'Force logout all sessions for any account that had a successful logon after the spray.', completed: false, priority: 'immediate' },
      { id: 'step-7', stage: 'eradicate', action: 'Force password reset on compromised accounts', description: 'Ensure passwords are changed to strong, unique values.', completed: false, priority: 'standard' },
      { id: 'step-8', stage: 'eradicate', action: 'Review all activity performed by compromised account', description: 'Check for persistence creation (4720, 4728, 7045) or data access.', completed: false, priority: 'standard' },
      { id: 'step-9', stage: 'recover', action: 'Re-enable accounts after password reset and MFA enrollment', description: 'Ensure MFA is active before restoring account access.', completed: false, priority: 'standard' },
      { id: 'step-10', stage: 'recover', action: 'Monitor re-enabled accounts for 72h hyper-care', description: 'Set enhanced alerting on the account for 3 days post-recovery.', completed: false, priority: 'followup' },
      { id: 'step-11', stage: 'improve', action: 'Implement account lockout policy (e.g., 10 failures in 10 minutes)', description: 'Prevents future brute force by automatically locking accounts.', completed: false, priority: 'followup' },
      { id: 'step-12', stage: 'improve', action: 'Enforce MFA for all privileged accounts', description: 'MFA prevents credential-only attacks from succeeding.', completed: false, priority: 'followup' },
    ],
    improvementRecommendations: [
      'Implement Azure AD/Okta Smart Lockout policies',
      'Deploy Conditional Access based on geolocation',
      'Enable password spray detection in SIEM',
      'Enforce MFA for all user accounts',
    ],
    escalationPath: 'P2: Senior Analyst review. If successful logon confirmed → P1: Incident Commander. Domain Admin compromise → C-Suite notification required.',
  },
  {
    id: 'PB-002',
    name: 'Suspicious PowerShell Execution Response',
    incidentCategory: 'ProcessExecution',
    severity: 'high',
    overview: 'Malicious PowerShell execution, particularly encoded/obfuscated commands, spawned from unusual parent processes (Office, browsers) or using known attack patterns.',
    whyItMatters: 'PowerShell is the most commonly abused tool for post-exploitation. Encoded payloads hide malicious intent and enable fileless malware, C2 communications, and data exfiltration.',
    detectionIndicators: [
      'Event 4688 — powershell.exe with -enc or -EncodedCommand arguments',
      'Event 4688 — PowerShell spawned from Office process (winword.exe, excel.exe)',
      'Event 4688 — PowerShell downloading from internet (IEX, Invoke-WebRequest)',
      'PowerShell ScriptBlock logging (Event 4104) showing suspicious commands',
    ],
    steps: [
      { id: 'step-1', stage: 'investigate', action: 'Decode the Base64 encoded command', description: 'Use CyberChef or PowerShell to decode the -enc argument and reveal the true payload.', completed: false, priority: 'immediate' },
      { id: 'step-2', stage: 'investigate', action: 'Identify the parent process', description: 'Office apps spawning PowerShell = malicious macro. WMI spawning PS = LOLBin abuse.', completed: false, priority: 'immediate' },
      { id: 'step-3', stage: 'investigate', action: 'Review network connections from PowerShell process', description: 'Look for connections to external IPs, known malicious domains, or unusual ports.', completed: false, priority: 'immediate' },
      { id: 'step-4', stage: 'investigate', action: 'Check for file drops or registry modifications', description: 'Malicious PS often drops payloads or creates persistence via registry run keys.', completed: false, priority: 'immediate' },
      { id: 'step-5', stage: 'contain', action: 'Isolate the affected host via EDR', description: 'Network-isolate the host to prevent C2 communication or lateral movement.', completed: false, priority: 'immediate' },
      { id: 'step-6', stage: 'contain', action: 'Kill the malicious PowerShell process if still running', description: 'Use EDR remote process termination to stop active execution.', completed: false, priority: 'immediate' },
      { id: 'step-7', stage: 'eradicate', action: 'Delete all files dropped by the PowerShell process', description: 'Remove any payloads, scripts, or tools dropped to disk.', completed: false, priority: 'standard' },
      { id: 'step-8', stage: 'eradicate', action: 'Remove registry persistence keys', description: 'Check and clean HKCU\\Run, HKLM\\Run, and Scheduled Tasks.', completed: false, priority: 'standard' },
      { id: 'step-9', stage: 'recover', action: 'Restore host from clean image if system integrity is uncertain', description: 'If memory-resident malware is suspected, reimaging is the safest path.', completed: false, priority: 'standard' },
      { id: 'step-10', stage: 'improve', action: 'Enable PowerShell Constrained Language Mode', description: 'Restricts advanced PS features used by attackers while allowing admin scripts.', completed: false, priority: 'followup' },
      { id: 'step-11', stage: 'improve', action: 'Deploy AMSI (Antimalware Scan Interface)', description: 'AMSI scans PowerShell scripts at runtime, catching obfuscated payloads.', completed: false, priority: 'followup' },
    ],
    improvementRecommendations: [
      'Enable Script Block Logging (Event 4104) enterprise-wide',
      'Implement PowerShell Constrained Language Mode',
      'Deploy AMSI integration with AV',
      'Block macro execution in Office via GPO',
    ],
    escalationPath: 'P2: Senior Analyst. If C2 communication confirmed or lateral movement detected → P1: Incident Commander.',
  },
  {
    id: 'PB-003',
    name: 'Unauthorized Service Installation Response',
    incidentCategory: 'ServiceInstallation',
    severity: 'critical',
    overview: 'A new Windows service was installed from an unusual or unauthorized path, indicating possible persistence mechanism installation, PsExec lateral movement, or ransomware deployment.',
    whyItMatters: 'Malicious services run at SYSTEM level and persist across reboots. PsExec-based lateral movement and ransomware commonly use services for execution and persistence.',
    detectionIndicators: [
      'Event 7045 — Service installed from Temp, AppData, or Public directories',
      'Event 7045 — Service name matching known malware patterns (PSEXESVC)',
      'Event 7045 followed immediately by Event 4688 with service binary path',
      'Service binary not signed by a trusted publisher',
    ],
    steps: [
      { id: 'step-1', stage: 'investigate', action: 'Examine the service binary path', description: 'Verify if the path is a trusted directory. Temp/Public/AppData paths are immediately suspicious.', completed: false, priority: 'immediate' },
      { id: 'step-2', stage: 'investigate', action: 'Check binary signature and hash', description: 'Verify the file hash against threat intel feeds (VirusTotal). Unsigned binaries are high-risk.', completed: false, priority: 'immediate' },
      { id: 'step-3', stage: 'investigate', action: 'Correlate with Event 4688 for execution evidence', description: 'Confirm the service actually executed and what child processes it spawned.', completed: false, priority: 'immediate' },
      { id: 'step-4', stage: 'contain', action: 'Stop and disable the malicious service', description: 'Use sc.exe or PowerShell to stop and disable the service immediately.', completed: false, priority: 'immediate' },
      { id: 'step-5', stage: 'contain', action: 'Isolate the host via EDR', description: 'Network-isolate to prevent C2 communication or further lateral movement.', completed: false, priority: 'immediate' },
      { id: 'step-6', stage: 'eradicate', action: 'Delete the malicious service binary', description: 'Remove the executable from disk. Take a forensic copy first.', completed: false, priority: 'standard' },
      { id: 'step-7', stage: 'eradicate', action: 'Remove service registry key', description: 'Delete HKLM\\SYSTEM\\CurrentControlSet\\Services\\[ServiceName]', completed: false, priority: 'standard' },
      { id: 'step-8', stage: 'eradicate', action: 'Scan for additional services created from same origin', description: 'The attacker may have created services on other hosts via lateral movement.', completed: false, priority: 'standard' },
      { id: 'step-9', stage: 'recover', action: 'Reimport registry hive or restore from clean backup', description: 'Ensure the service is fully purged from all registry hives.', completed: false, priority: 'standard' },
      { id: 'step-10', stage: 'improve', action: 'Implement application whitelisting via AppLocker', description: 'Prevents execution of unauthorized binaries including malicious service payloads.', completed: false, priority: 'followup' },
    ],
    improvementRecommendations: [
      'Deploy AppLocker or WDAC for application control',
      'Alert on services installed from non-standard paths',
      'Implement integrity monitoring on service registry keys',
      'Restrict service installation to privileged, audited accounts only',
    ],
    escalationPath: 'P1: Immediate Incident Commander notification. Service installation on DC = CISO notification required.',
  },
  {
    id: 'PB-004',
    name: 'Privilege Escalation — Domain Admin Group Modification',
    incidentCategory: 'PrivilegeEscalation',
    severity: 'critical',
    overview: 'An unauthorized account addition to Domain Admins, Enterprise Admins, or other Tier 0 privileged groups without an approved change management request.',
    whyItMatters: 'Domain Admin access grants an attacker complete control over the Active Directory environment, enabling mass credential harvesting, GPO manipulation, and domain-wide ransomware deployment.',
    detectionIndicators: [
      'Event 4728 — Account added to Domain Admins or Enterprise Admins',
      'Event 4728 performed by a non-standard administrative account',
      'Event 4728 without a corresponding approved change ticket',
      'Event 4728 outside of business hours',
    ],
    steps: [
      { id: 'step-1', stage: 'investigate', action: 'Verify against ITSM change management system', description: 'Check if an approved ticket exists for this group modification. No ticket = immediate escalation.', completed: false, priority: 'immediate' },
      { id: 'step-2', stage: 'investigate', action: 'Determine how the Subject User account was accessed', description: 'Correlate with 4625/4624 events to determine if the account was compromised.', completed: false, priority: 'immediate' },
      { id: 'step-3', stage: 'investigate', action: 'Review all actions by the added account since elevation', description: 'Check for any GPO changes, credential harvesting, or additional account creations.', completed: false, priority: 'immediate' },
      { id: 'step-4', stage: 'contain', action: 'Immediately remove the unauthorized account from the group', description: 'Remove the account from Domain Admins. Document the action with timestamp.', completed: false, priority: 'immediate' },
      { id: 'step-5', stage: 'contain', action: 'Disable the unauthorized account', description: 'Prevent any further use of the account until investigation is complete.', completed: false, priority: 'immediate' },
      { id: 'step-6', stage: 'contain', action: 'Disable the Subject User account if compromised', description: 'If the account that made the modification was compromised, disable it immediately.', completed: false, priority: 'immediate' },
      { id: 'step-7', stage: 'eradicate', action: 'Audit all changes made while unauthorized access was active', description: 'Review GPO changes, new accounts, certificate changes, and Trust modifications.', completed: false, priority: 'standard' },
      { id: 'step-8', stage: 'eradicate', action: 'Force password rotation for ALL Domain Admin accounts', description: 'If Domain Admin credentials may have been exposed, rotate all DA passwords.', completed: false, priority: 'standard' },
      { id: 'step-9', stage: 'recover', action: 'Review and revert any unauthorized GPO changes', description: 'Check for backdoor GPOs, logon scripts, or security setting weakening.', completed: false, priority: 'standard' },
      { id: 'step-10', stage: 'improve', action: 'Implement Just-in-Time (JIT) Privileged Access', description: 'Use Azure PIM or PAM solutions for time-limited privileged access.', completed: false, priority: 'followup' },
      { id: 'step-11', stage: 'improve', action: 'Enable Protected Users security group for all DA accounts', description: 'Prevents NTLM authentication and forces Kerberos for privileged accounts.', completed: false, priority: 'followup' },
    ],
    improvementRecommendations: [
      'Implement Privileged Identity Management (PIM/PAM)',
      'Enable Protected Users security group for all Tier 0 accounts',
      'Deploy Privileged Access Workstations (PAWs)',
      'Require dual-approval for any Tier 0 group modifications',
    ],
    escalationPath: 'P1: Immediate Incident Commander and CISO notification. Active Domain Admin compromise requires C-Suite briefing.',
  },
];
