import type { Incident, SecurityEvent, IncidentCategory } from '../types';
import { CorrelationEngine } from '../core/CorrelationEngine';

// =============================================
// ETD — Mock Incidents & Security Events
// Dynamically Generated by the Correlation Engine
// =============================================

// Raw Event Stream 1: Brute Force -> Successful Logon
const bruteForceStream: SecurityEvent[] = [
  ...Array.from({ length: 12 }).map((_, i) => ({
    id: `evt-bf-${i}`,
    eventId: 'WEL-4625',
    eventName: 'Failed Logon',
    category: 'Authentication' as IncidentCategory,
    timestamp: new Date(Date.now() - (30 - i) * 60000).toISOString(),
    hostname: 'EXCHANGE-01',
    user: `user${i % 4}`,
    sourceIp: '91.108.4.177',
    severity: 'medium' as const,
    source: 'Windows Security',
    description: 'A user account failed to log on due to a bad password.',
    mitreMapping: [],
    defenseChainMapping: { detect: 'Multiple failed logons detected' },
    raw: { LogonType: 3, FailureReason: '0xC000006A' },
  })),
  {
    id: 'evt-bf-success',
    eventId: 'WEL-4624',
    eventName: 'Successful Logon',
    category: 'Authentication' as IncidentCategory,
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    hostname: 'EXCHANGE-01',
    user: 'user2',
    sourceIp: '91.108.4.177',
    severity: 'high',
    source: 'Windows Security',
    description: 'A successful logon occurred immediately following a brute force attempt.',
    mitreMapping: [{ tacticId: 'TA0001', tacticName: 'Initial Access', techniqueId: 'T1078', techniqueName: 'Valid Accounts' }],
    defenseChainMapping: { triage: 'Verify if the user context is expected' },
    raw: { LogonType: 3, AuthPackage: 'NTLMv2' },
  }
];

// Raw Event Stream 2: Persistence via Service Creation
const persistenceStream: SecurityEvent[] = [
  {
    id: 'evt-pers-1',
    eventId: 'WEL-4624',
    eventName: 'Successful Logon',
    category: 'Authentication' as IncidentCategory,
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    hostname: 'WORKSTATION-07',
    user: 'administrator',
    sourceIp: '185.220.101.47',
    severity: 'medium',
    source: 'Windows Security',
    description: 'Remote interactive logon by administrator.',
    mitreMapping: [],
    defenseChainMapping: {},
    raw: { LogonType: 3, AuthPackage: 'NTLMv2' },
  },
  {
    id: 'evt-pers-2',
    eventId: 'WEL-4688',
    eventName: 'Process Creation',
    category: 'ProcessExecution' as IncidentCategory,
    timestamp: new Date(Date.now() - 119 * 60000).toISOString(),
    hostname: 'WORKSTATION-07',
    user: 'administrator',
    sourceIp: '185.220.101.47',
    severity: 'critical',
    source: 'Windows Security',
    description: 'Suspicious command prompt execution.',
    mitreMapping: [{ tacticId: 'TA0002', tacticName: 'Execution', techniqueId: 'T1059.003', techniqueName: 'Windows Command Shell' }],
    defenseChainMapping: { investigate: 'Analyze the spawned process arguments' },
    raw: { NewProcessName: 'C:\\Windows\\System32\\cmd.exe' },
  },
  {
    id: 'evt-pers-3',
    eventId: 'WEL-7045',
    eventName: 'New Service Installed',
    category: 'ServiceInstallation' as IncidentCategory,
    timestamp: new Date(Date.now() - 118 * 60000).toISOString(),
    hostname: 'WORKSTATION-07',
    user: 'administrator',
    sourceIp: undefined,
    severity: 'critical',
    source: 'System',
    description: 'A new service was installed on the system, often used for persistence.',
    mitreMapping: [{ tacticId: 'TA0003', tacticName: 'Persistence', techniqueId: 'T1543.003', techniqueName: 'Windows Service' }],
    defenseChainMapping: { contain: 'Disable the rogue service immediately' },
    raw: { ServiceName: 'UpdaterSvc', ImagePath: 'C:\\Users\\Public\\AppData\\Temp\\payload.exe' },
  }
];

// Raw Event Stream 3: Lateral Movement via Rogue Account
const lateralStream: SecurityEvent[] = [
  {
    id: 'evt-lat-1',
    eventId: 'WEL-4720',
    eventName: 'User Account Created',
    category: 'UserAccountChanges' as IncidentCategory,
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    hostname: 'DC-01',
    user: 'administrator',
    sourceIp: undefined,
    severity: 'high',
    source: 'Windows Security',
    description: 'A new user account was created by the administrator.',
    mitreMapping: [{ tacticId: 'TA0003', tacticName: 'Persistence', techniqueId: 'T1136.001', techniqueName: 'Local Account' }],
    defenseChainMapping: { triage: 'Confirm if this account creation was part of a planned change' },
    raw: { TargetUserName: 'svc_backup01' },
  },
  {
    id: 'evt-lat-2',
    eventId: 'WEL-4728',
    eventName: 'Member Added to Group',
    category: 'UserAccountChanges' as IncidentCategory,
    timestamp: new Date(Date.now() - 59 * 60000).toISOString(),
    hostname: 'DC-01',
    user: 'administrator',
    sourceIp: undefined,
    severity: 'critical',
    source: 'Windows Security',
    description: 'A user was added to a highly privileged group.',
    mitreMapping: [{ tacticId: 'TA0004', tacticName: 'Privilege Escalation', techniqueId: 'T1078.002', techniqueName: 'Domain Accounts' }],
    defenseChainMapping: { investigate: 'Verify authorization for Domain Admin addition' },
    raw: { MemberName: 'svc_backup01', GroupName: 'Domain Admins' },
  },
  {
    id: 'evt-lat-3',
    eventId: 'WEL-4624',
    eventName: 'Successful Logon',
    category: 'LateralMovement' as IncidentCategory,
    timestamp: new Date(Date.now() - 58 * 60000).toISOString(),
    hostname: 'DC-02',
    user: 'svc_backup01',
    sourceIp: '10.0.1.55',
    severity: 'critical',
    source: 'Windows Security',
    description: 'Logon by newly created privileged account on a secondary domain controller.',
    mitreMapping: [{ tacticId: 'TA0008', tacticName: 'Lateral Movement', techniqueId: 'T1021.002', techniqueName: 'SMB/Windows Admin Shares' }],
    defenseChainMapping: { contain: 'Isolate DC-02 and disable svc_backup01' },
    raw: { LogonType: 3 },
  }
];

// Generic Stream: Uncorrelated high severity event
const isolatedStream: SecurityEvent[] = [
  {
    id: 'evt-iso-1',
    eventId: 'WEL-4688',
    eventName: 'Process Creation',
    category: 'MalwareActivity' as IncidentCategory,
    timestamp: new Date(Date.now() - 200 * 60000).toISOString(),
    hostname: 'LAPTOP-SALES-04',
    user: 'psmith',
    sourceIp: undefined,
    severity: 'high',
    source: 'Windows Security',
    description: 'Encoded PowerShell execution detected.',
    mitreMapping: [{ tacticId: 'TA0002', tacticName: 'Execution', techniqueId: 'T1059.001', techniqueName: 'PowerShell' }],
    defenseChainMapping: { triage: 'Decode the PowerShell payload' },
    raw: { CommandLine: 'powershell.exe -enc SQBuAHYAbwBrAGUALQ...' },
  }
];

// Initialize the Engine and generate incidents
const engine = new CorrelationEngine();

engine.ingest(bruteForceStream);
const inc1 = engine.analyze();

engine.ingest(persistenceStream);
const inc2 = engine.analyze();

engine.ingest(lateralStream);
const inc3 = engine.analyze();

engine.ingest(isolatedStream);
const inc4 = engine.analyze();

export const mockIncidents: Incident[] = [
  ...inc1,
  ...inc2,
  ...inc3,
  ...inc4,
].map((inc, idx) => ({
  ...inc,
  // Hardcode specific statuses/priorities to make the UI look good for demo
  status: idx === 0 ? 'active' : idx === 1 ? 'investigating' : idx === 2 ? 'contained' : 'closed',
  id: `INC-2024-08${47 - idx * 4}`, // Keep sequential looking IDs
}));

// Fallback legacy array for UI elements that directly map to events instead of incidents
export const mockEvents: SecurityEvent[] = [
  ...bruteForceStream,
  ...persistenceStream,
  ...lateralStream,
  ...isolatedStream
];

export const mockTimelineData = [
  { time: '00:00', events: 2, severity: 1 },
  { time: '01:00', events: 5, severity: 2 },
  { time: '02:00', events: 14, severity: 5 },
  { time: '03:00', events: 47, severity: 8 },
  { time: '04:00', events: 62, severity: 10 },
  { time: '05:00', events: 31, severity: 7 },
  { time: '06:00', events: 18, severity: 4 },
  { time: '07:00', events: 9, severity: 3 },
  { time: '08:00', events: 4, severity: 2 },
];

export const mockSeverityDistribution = [
  { name: 'Critical', value: 4, color: '#f87171' },
  { name: 'High', value: 8, color: '#fb923c' },
  { name: 'Medium', value: 15, color: '#fbbf24' },
  { name: 'Low', value: 22, color: '#22d3ee' },
  { name: 'Info', value: 41, color: '#64748b' },
];

export const mockMitreData = [
  { tactic: 'Initial Access', count: 12, color: '#f87171' },
  { tactic: 'Execution', count: 8, color: '#fb923c' },
  { tactic: 'Persistence', count: 14, color: '#fbbf24' },
  { tactic: 'Privilege Escalation', count: 6, color: '#22d3ee' },
  { tactic: 'Defense Evasion', count: 5, color: '#818cf8' },
  { tactic: 'Credential Access', count: 18, color: '#60a5fa' },
  { tactic: 'Lateral Movement', count: 9, color: '#34d399' },
  { tactic: 'Exfiltration', count: 3, color: '#a78bfa' },
];

export const mockDefenseChainStats = [
  { stage: 'Detect', active: 4, resolved: 28 },
  { stage: 'Triage', active: 2, resolved: 24 },
  { stage: 'Investigate', active: 3, resolved: 19 },
  { stage: 'Contain', active: 1, resolved: 16 },
  { stage: 'Eradicate', active: 1, resolved: 13 },
  { stage: 'Recover', active: 0, resolved: 11 },
  { stage: 'Improve', active: 0, resolved: 9 },
];
